# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf9968d06e48ca888c891a16faae0f709404d910027beef67cd1d1570e687d1bdeccaea5a26b6dc22245da9676286ddb1814b2362caf400e1d1c4cf51c214082

test:
  secret_key_base: 5064fce1abbe8ff3426c2326174018a6387afafc6cc9d3da37e43dfe52022dcb46a4277ec05893386c4bb72a425165d5912e7c941ed207418bce5dcebc631b53

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
